import { motion } from 'framer-motion';
import { BookOpen, Home, Sparkles, Heart, Eye, MessageCircle, Mic2, ArrowDown, ArrowRight, MapPin, Speech, CircleDot, Network, DoorOpen } from 'lucide-react';
import SectionNumber from './SectionNumber';

type Person = { name: string; role: string; detail: string };
type Chapter = { id: string; number: string; presenter: string; title: string; subtitle: string; intro: string; talk: string; people: Person[]; board: string[]; note?: string; extras?: string };

const chapters: Chapter[] = [
  {
    id: 'chapitre-yahya', number: '02', presenter: 'Yahya Riyaf', title: 'Sidi Mohammed et sa famille', subtitle: 'Le regard de l’enfant · le cœur du roman',
    intro: 'Le premier cercle du roman est celui du foyer : un enfant, sa mère, son père et un petit monde intérieur auquel il se réfugie.',
    talk: 'Pour comprendre les autres personnages, il faut d’abord écouter celui qui raconte. Sidi Mohammed est un enfant de six ans qui vit avec ses parents dans la médina de Fès. Le récit est écrit à la première personne : nous découvrons les événements à travers ses sensations d’enfant, tandis que le narrateur adulte revient sur ses souvenirs. Lalla Zoubida, sa mère, est très présente et s’inquiète du sort de sa famille. Son père, Maâlem Abdeslam, est tisserand. L’objet central du monde intime de l’enfant est sa boîte : elle contient de menus objets — boutons, cabochon de verre, chaînette — que son imagination transforme en compagnons merveilleux. Plus tard, le père perd son capital au souk et part travailler près de Fès. Son absence inquiète toute la famille. Son retour rétablit la joie de la maison, même si le narrateur reste un enfant rêveur et solitaire.',
    people: [
      { name: 'Sidi Mohammed', role: 'Enfant · narrateur-personnage', detail: 'Il a six ans dans les souvenirs racontés. Sensible, solitaire et imaginatif, il observe les adultes sans toujours comprendre leurs soucis. Le passage entre son regard d’enfant et le recul du narrateur adulte donne au récit sa profondeur de mémoire.' },
      { name: 'Lalla Zoubida', role: 'La mère', detail: 'Elle protège son fils et s’inquiète pour la famille. Elle se confie à son amie Lalla Aïcha; quand son mari part, elle cherche du soutien et de l’espoir auprès des proches et de pratiques populaires.' },
      { name: 'Maâlem Abdeslam', role: 'Le père · tisserand', detail: 'Artisan calme et discret. Après avoir perdu son capital, il quitte provisoirement Fès pour travailler aux environs et pouvoir reprendre son activité. Son départ constitue le grand bouleversement du récit.' },
    ],
    board: ['Sidi Mohammed : enfant de 6 ans; narrateur à la première personne', 'Parents : Lalla Zoubida + Maâlem Abdeslam, tisserand', 'Objet-refuge : la boîte transforme de petits objets en monde imaginaire', 'Événement-clé : perte du capital → départ du père → attente → retour'],
    note: 'À retenir : l’œuvre est souvent étudiée comme un roman autobiographique, mais Sidi Mohammed est le narrateur-personnage, pas le nom réel de l’auteur. La boîte est un objet symbolique et un refuge par l’imagination; le récit ne dit pas qu’elle possède réellement des pouvoirs magiques.'
  },
  {
    id: 'chapitre-rayan', number: '03', presenter: 'Rayan Rchouki', title: 'Dar Chouafa : le voisinage', subtitle: 'Une maison où les destins se croisent',
    intro: 'La maison n’est pas un simple décor. Ses étages réunissent plusieurs familles et rendent visibles les relations quotidiennes : entraide, disputes, nouvelles et fêtes.',
    talk: 'Dar Chouafa est l’un des lieux essentiels du roman. Le guide de lecture distingue les habitants par étage : au rez-de-chaussée vit Lalla Kanza, appelée la Chouafa; au premier étage, Rahma, son mari Driss El Aouad et leur fille Zineb; au deuxième, la famille de Sidi Mohammed partage l’espace avec Fatma Bziouya et son mari Allal. Cette proximité explique pourquoi les personnages entendent les nouvelles et interviennent dans les malheurs des autres. Un exemple important est la disparition de Zineb. Rahma est désespérée, et les voisines se rassemblent pour la consoler. Lalla Zoubida oublie alors sa dispute précédente avec Rahma et prend part à la douleur commune. L’épisode montre la solidarité du voisinage, mais aussi la manière dont l’enfant observe les émotions des adultes. Le fqih du msid élargit ce monde : l’école est un autre lieu qui rythme les journées de Sidi Mohammed.',
    people: [
      { name: 'Lalla Kanza · la Chouafa', role: 'Voyante · rez-de-chaussée', detail: 'Habitante de Dar Chouafa et voyante connue dans le quartier. La maison tire son nom de sa présence. Elle introduit les croyances populaires et le mystère dans le quotidien raconté par l’enfant.' },
      { name: 'Rahma & Zineb', role: 'Mère et fille · 1er étage', detail: 'Rahma est la voisine de Lalla Zoubida et la mère de Zineb. Quand Zineb se perd, la maison entière s’émeut. Le malheur fait taire, pour un temps, les anciennes querelles.' },
      { name: 'Driss El Aouad', role: 'Père de Zineb', detail: 'Fabricant de charrues, mari de Rahma. Son prénom est à distinguer de Driss « le teigneux », qui travaille auprès de Maâlem Abdeslam.' },
      { name: 'Fatma Bziouya & Allal', role: 'Voisins · 2e étage', detail: 'Fatma partage le deuxième étage avec la famille du narrateur. Son mari Allal est jardinier. Leurs habitudes font partie des détails concrets de la vie de Dar Chouafa.' },
      { name: 'Le fqih', role: 'Maître du msid', detail: 'Le maître de l’école coranique. Ses leçons, les récitations et sa baguette marquent l’expérience scolaire de Sidi Mohammed et nourrissent certains de ses cauchemars.' },
    ],
    board: ['Rez-de-chaussée : Lalla Kanza / la Chouafa', '1er étage : Rahma + Driss El Aouad + Zineb', '2e étage : famille du narrateur + Fatma Bziouya et Allal', 'Épisode à raconter : Zineb se perd → les voisines se rassemblent → solidarité'],
    note: 'La graphie du prénom de la voyante varie entre certaines fiches scolaires (« Kanza » / « Kenza »). La fiche AlloSchool utilisée pour les personnages écrit « Lalla Kanza »; vérifiez le prénom dans votre exemplaire.'
  },
  {
    id: 'chapitre-lgharib', number: '04', presenter: 'Lgharib', title: 'Le cercle élargi', subtitle: 'Amitié, récits rapportés et histoires dans l’histoire',
    intro: 'Les personnages extérieurs au foyer élargissent le récit. Certains apparaissent dans l’action; d’autres sont connus par les confidences et les histoires que les adultes transmettent.',
    talk: 'Le cercle des personnages ne s’arrête pas à Dar Chouafa. Lalla Aïcha, ancienne voisine et amie de Lalla Zoubida, lui raconte ses difficultés avec Moulay Larbi. Celui-ci est babouchier; ses revers professionnels et ses choix conjugaux forment une histoire secondaire qui revient dans les conversations. Salama, la marieuse, est liée à cet épisode. D’autres personnages nourrissent surtout l’imagination de Sidi Mohammed : Abdellah l’épicier est associé aux récits qui le fascinent, tandis que Sidi El Arafi est consulté par les deux femmes lorsqu’elles sont inquiètes. Il faut aussi distinguer les deux Driss : Driss El Aouad est le voisin fabricant de charrues; Driss le teigneux aide le père du narrateur. Enfin, Rahma raconte l’histoire de Sidi Othmane et de Lalla Khadija : c’est un récit enchâssé, une histoire racontée à l’intérieur du roman. Ces voix rendent le monde du livre plus vaste que le seul regard de l’enfant.',
    people: [
      { name: 'Lalla Aïcha', role: 'Amie de Lalla Zoubida', detail: 'Ancienne voisine et confidente. Ses visites et ses confidences rapprochent les deux femmes; ses problèmes conjugaux et financiers donnent lieu à un récit secondaire suivi par le narrateur.' },
      { name: 'Moulay Larbi', role: 'Babouchier · mari de Lalla Aïcha', detail: 'Artisan fabricant de babouches. Ses difficultés avec son associé, puis son remariage et son retour auprès de Lalla Aïcha, constituent une intrigue secondaire rapportée dans les conversations.' },
      { name: 'Abdellah l’épicier', role: 'Personnage des récits', detail: 'L’enfant est fasciné par les histoires qui lui sont associées et qu’il entend notamment par l’intermédiaire de son père. Abdellah relie le quotidien des adultes au monde merveilleux de l’imagination.' },
      { name: 'Sidi El Arafi', role: 'Voyant consulté', detail: 'Lalla Zoubida et Lalla Aïcha viennent le consulter pendant une période d’angoisse. Les fiches de lecture le décrivent comme aveugle; il réconforte les deux femmes par ses paroles.' },
      { name: 'Driss « le teigneux »', role: 'Aide de Maâlem Abdeslam', detail: 'Il aide le père dans son travail et fait des commissions. Ce n’est pas Driss El Aouad : pour l’exposé, préciser son surnom évite la confusion.' },
      { name: 'Salama', role: 'Marieuse', detail: 'Figure secondaire associée aux événements autour de Moulay Larbi. Son métier explique comment elle intervient dans les nouvelles et les arrangements matrimoniaux.' },
    ],
    board: ['Lalla Zoubida ↔ Lalla Aïcha : amitié et confidences', 'Moulay Larbi : babouchier; son histoire forme une intrigue secondaire', 'Abdellah : récits qui stimulent l’imagination de l’enfant', 'Sidi Othmane + Lalla Khadija : récit raconté par Rahma (récit enchâssé)'],
    extras: 'Autres figures à citer brièvement si le temps le permet : Sidi Othmane et Lalla Khadija dans le récit rapporté par Rahma; Sidi Mohammed ben Tahar, le coiffeur du quartier; Zhor, voisine de Lalla Aïcha.',
    note: 'Deux distinctions importantes pour l’exposé : Sidi El Arafi est le voyant consulté par les femmes, tandis que Lalla Kanza est la Chouafa de Dar Chouafa; et Driss El Aouad n’est pas Driss « le teigneux ».'
  }
];

function Heading({ chapter }: { chapter: Chapter }) {
  return <div className="max-w-6xl mx-auto px-4 sm:px-6">
    <div className="eyebrow mb-5"><span className="w-1 h-1 rounded-full bg-warm" />Chapitre {chapter.number} · Présenté par {chapter.presenter}</div>
    <h2 className="font-serif text-4xl sm:text-5xl md:text-6xl text-ink dark:text-ivory leading-[1.04]">{chapter.title}</h2>
    <p className="mt-3 text-xs sm:text-sm uppercase tracking-[0.17em] text-warm-dark dark:text-gold-light">{chapter.subtitle}</p>
  </div>;
}

function SpeakerText({ chapter, className = '' }: { chapter: Chapter; className?: string }) {
  return <div className={`bezel-outer shadow-ambient ${className}`}><div className="bezel-inner p-7 sm:p-9 md:p-11">
    <div className="flex items-center gap-3 mb-5"><span className="w-9 h-9 rounded-full bg-warm/[0.08] border border-warm/15 flex items-center justify-center"><Mic2 size={17} className="text-warm-dark dark:text-gold-light"/></span><p className="text-[10px] uppercase tracking-[0.21em] text-warm-dark dark:text-gold-light">Texte oral · {chapter.presenter}</p></div>
    <p className="text-lg sm:text-xl md:text-[1.35rem] text-ink dark:text-ivory leading-[1.8]">{chapter.talk}</p>
  </div></div>;
}


function FamilyChapter({ chapter }: { chapter: Chapter }) {
  return <section id={chapter.id} className="section-pad relative pt-8 scroll-mt-20">
    <div className="max-w-6xl mx-auto px-4 sm:px-6">
      <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-9"><Heading chapter={chapter}/></motion.div>
      <div className="grid lg:grid-cols-[1.2fr_0.8fr] gap-5 items-stretch mb-6">
        <SpeakerText chapter={chapter} />
        <div className="bezel-outer shadow-ambient-sm"><div className="bezel-inner p-6 sm:p-8 h-full flex flex-col justify-center">
          <p className="text-[10px] uppercase tracking-[0.2em] text-warm-dark dark:text-gold-light mb-6">Arbre du foyer</p>
          <div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-ink/8 dark:border-white/10 p-4 text-center"><span className="text-[9px] uppercase tracking-[0.15em] text-ink-faint dark:text-ivory-faint">Mère</span><p className="font-serif text-lg sm:text-xl text-ink dark:text-ivory mt-1">Lalla Zoubida</p></div><div className="rounded-2xl border border-ink/8 dark:border-white/10 p-4 text-center"><span className="text-[9px] uppercase tracking-[0.15em] text-ink-faint dark:text-ivory-faint">Père · tisserand</span><p className="font-serif text-lg sm:text-xl text-ink dark:text-ivory mt-1">Maâlem Abdeslam</p></div></div>
          <div className="flex justify-center py-3 text-warm-dark dark:text-gold-light"><ArrowDown size={19}/></div>
          <div className="rounded-2xl border border-warm/20 bg-warm/[0.055] p-5 text-center"><span className="text-[9px] uppercase tracking-[0.15em] text-warm-dark dark:text-gold-light">Enfant · narrateur</span><p className="font-serif text-2xl sm:text-3xl text-ink dark:text-ivory mt-1">Sidi Mohammed</p></div>
          <div className="mt-4 rounded-2xl bg-ink/[0.035] dark:bg-white/[0.035] p-4 text-center"><p className="text-[9px] uppercase tracking-[0.16em] text-ink-faint dark:text-ivory-faint">Son refuge intérieur</p><p className="font-serif italic text-lg text-ink-muted dark:text-ivory-muted mt-1">La boîte à merveilles</p></div>
        </div></div>
      </div>
      <div className="mb-6 rounded-2xl border border-warm/15 bg-warm/[0.045] p-5 sm:p-6">
        <div className="flex items-center gap-2 mb-4"><CircleDot size={16} className="text-warm-dark dark:text-gold-light"/><h3 className="font-serif text-xl text-ink dark:text-ivory">Le tournant de l’histoire</h3></div>
        <div className="grid sm:grid-cols-4 gap-3">{['Vie quotidienne à Fès', 'Le père perd son capital', 'Départ et inquiétude', 'Retour du père'].map((step, i) => <div key={step} className="flex items-center gap-3"><span className="w-8 h-8 shrink-0 rounded-full border border-warm/25 flex items-center justify-center font-serif text-sm text-warm-dark dark:text-gold-light">{i + 1}</span><p className="text-sm sm:text-base text-ink-muted dark:text-ivory-muted leading-snug">{step}</p>{i < 3 && <ArrowRight size={14} className="hidden sm:block shrink-0 text-warm/60"/>}</div>)}</div>
      </div>
      <h3 className="font-serif text-2xl sm:text-3xl text-ink dark:text-ivory mb-4">Trois portraits essentiels</h3>
      <div className="grid md:grid-cols-3 gap-4 mb-6">{chapter.people.map((person, i) => <article key={person.name} className={`relative overflow-hidden rounded-2xl border border-ink/7 dark:border-white/8 p-6 sm:p-7 ${i === 0 ? 'bg-warm/[0.045]' : 'bg-white/25 dark:bg-white/[0.02]'}`}><span className="absolute right-5 top-2 font-serif text-6xl text-ink/[0.045] dark:text-white/[0.045]">0{i + 1}</span><p className="text-[9px] uppercase tracking-[0.16em] text-warm-dark dark:text-gold-light mb-3">{person.role}</p><h4 className="font-serif text-xl sm:text-2xl text-ink dark:text-ivory mb-3">{person.name}</h4><p className="text-base text-ink-muted dark:text-ivory-muted leading-[1.7]">{person.detail}</p></article>)}</div>
      <div className="rounded-2xl border border-ink/8 dark:border-white/10 px-5 py-4 mb-5 flex gap-3 items-start"><Sparkles size={17} className="mt-1 text-warm-dark dark:text-gold-light shrink-0"/><p className="text-sm sm:text-base text-ink-muted dark:text-ivory-muted leading-relaxed">{chapter.note}</p></div>
      <div className="rounded-[1.5rem] bg-ink dark:bg-obsidian-light p-6 sm:p-8 text-cream dark:text-ivory shadow-ambient mt-6"><p className="text-[9px] uppercase tracking-[0.2em] text-gold-light mb-5">La chaîne à retenir</p><div className="grid sm:grid-cols-2 gap-3">{chapter.board.map((line, i) => <p key={line} className="flex gap-3 items-start border-t border-white/10 pt-3"><span className="font-serif text-gold-light">0{i + 1}</span><span className="text-sm sm:text-base text-ivory-light leading-relaxed">{line}</span></p>)}</div></div>
    </div>
  </section>;
}

function NeighbourChapter({ chapter }: { chapter: Chapter }) {
  return <section id={chapter.id} className="section-pad relative pt-8 scroll-mt-20">
    <div className="max-w-6xl mx-auto px-4 sm:px-6">
      <div className="text-center mb-9"><div className="eyebrow mb-5"><span className="w-1 h-1 rounded-full bg-warm"/>Chapitre {chapter.number} · Présenté par {chapter.presenter}</div><h2 className="font-serif text-4xl sm:text-5xl md:text-6xl text-ink dark:text-ivory leading-[1.04]">Dar Chouafa : <span className="italic text-ink-light dark:text-ivory-muted">une maison vivante</span></h2><p className="mt-3 text-xs sm:text-sm uppercase tracking-[0.17em] text-warm-dark dark:text-gold-light">{chapter.subtitle}</p></div>
      <div className="bezel-outer shadow-ambient mb-6"><div className="bezel-inner p-7 sm:p-9 md:p-11"><div className="flex items-center gap-3 mb-5"><Speech size={19} className="text-warm-dark dark:text-gold-light"/><p className="text-[10px] uppercase tracking-[0.2em] text-warm-dark dark:text-gold-light">Rayan · texte oral</p></div><p className="text-lg sm:text-xl text-ink dark:text-ivory leading-[1.8]">{chapter.talk}</p></div></div>
      <div className="grid lg:grid-cols-[0.78fr_1.22fr] gap-5 items-stretch mb-6">
        <div className="bezel-outer shadow-ambient-sm"><div className="bezel-inner p-6 sm:p-8 h-full">
          <div className="flex justify-between items-center mb-5"><div><p className="text-[9px] uppercase tracking-[0.2em] text-warm-dark dark:text-gold-light">Plan de la maison</p><h3 className="font-serif text-2xl text-ink dark:text-ivory mt-1">Les étages</h3></div><Home size={21} className="text-warm-dark dark:text-gold-light"/></div>
          <div className="space-y-3">
            <div className="relative border border-ink/8 dark:border-white/10 rounded-2xl p-4 pl-16"><span className="absolute left-4 top-1/2 -translate-y-1/2 font-serif text-3xl text-ink-faint/60 dark:text-ivory-faint/60">02</span><p className="text-[9px] uppercase tracking-[0.15em] text-warm-dark dark:text-gold-light">Deuxième étage</p><p className="font-serif text-lg text-ink dark:text-ivory mt-1">La famille du narrateur</p><p className="text-sm text-ink-muted dark:text-ivory-muted mt-1">et Fatma Bziouya avec Allal</p></div>
            <div className="relative border border-ink/8 dark:border-white/10 rounded-2xl p-4 pl-16"><span className="absolute left-4 top-1/2 -translate-y-1/2 font-serif text-3xl text-ink-faint/60 dark:text-ivory-faint/60">01</span><p className="text-[9px] uppercase tracking-[0.15em] text-warm-dark dark:text-gold-light">Premier étage</p><p className="font-serif text-lg text-ink dark:text-ivory mt-1">Rahma, Driss El Aouad</p><p className="text-sm text-ink-muted dark:text-ivory-muted mt-1">et leur fille Zineb</p></div>
            <div className="relative border border-warm/20 bg-warm/[0.045] rounded-2xl p-4 pl-16"><span className="absolute left-4 top-1/2 -translate-y-1/2 font-serif text-3xl text-warm-dark/60 dark:text-gold-light/60">00</span><p className="text-[9px] uppercase tracking-[0.15em] text-warm-dark dark:text-gold-light">Rez-de-chaussée</p><p className="font-serif text-lg text-ink dark:text-ivory mt-1">Lalla Kanza · la Chouafa</p><p className="text-sm text-ink-muted dark:text-ivory-muted mt-1">voyante du quartier</p></div>
          </div>
          <div className="mt-4 flex gap-3 items-center rounded-xl bg-ink/[0.03] dark:bg-white/[0.03] p-3"><DoorOpen size={16} className="text-warm-dark dark:text-gold-light"/><p className="text-sm text-ink-muted dark:text-ivory-muted"><strong className="text-ink dark:text-ivory">Hors de la maison :</strong> le msid et son fqih</p></div>
        </div></div>
        <div className="flex flex-col gap-4">
          <div className="bezel-outer shadow-ambient-sm flex-1"><div className="bezel-inner p-6 sm:p-8 h-full"><p className="text-[9px] uppercase tracking-[0.2em] text-warm-dark dark:text-gold-light mb-5">Les personnages et leur place</p><div className="space-y-4">{chapter.people.map((person, i) => <div key={person.name} className="flex gap-4 border-b border-ink/5 dark:border-white/8 pb-4 last:border-0 last:pb-0"><span className="font-serif text-2xl text-ink-faint/50 dark:text-ivory-faint/50">0{i + 1}</span><div><div className="flex flex-wrap items-baseline gap-x-3 gap-y-1"><h4 className="font-serif text-lg sm:text-xl text-ink dark:text-ivory">{person.name}</h4><span className="text-[9px] uppercase tracking-[0.12em] text-warm-dark dark:text-gold-light">{person.role}</span></div><p className="mt-1 text-sm sm:text-base text-ink-muted dark:text-ivory-muted leading-relaxed">{person.detail}</p></div></div>)}</div></div></div>
        </div>
      </div>
      <div className="rounded-2xl bg-ink dark:bg-obsidian-light p-6 sm:p-8 text-cream dark:text-ivory shadow-ambient mb-5"><div className="flex flex-col md:flex-row md:items-center gap-5"><div className="md:w-1/4"><p className="text-[9px] uppercase tracking-[0.2em] text-warm-light dark:text-gold-light mb-2">Scène à raconter</p><h3 className="font-serif text-2xl sm:text-3xl">La disparition de Zineb</h3></div><div className="flex-1 flex flex-wrap items-center gap-2 sm:gap-3">{['Zineb se perd', 'Rahma s’affole', 'Les voisines accourent', 'La dispute s’efface'].map((part, i) => <div key={part} className="flex items-center gap-2"><span className="rounded-full border border-white/15 px-3 py-2 text-xs sm:text-sm text-ivory-light">{part}</span>{i < 3 && <ArrowRight size={14} className="text-warm-light"/>}</div>)}</div></div><p className="mt-5 border-t border-white/10 pt-4 text-sm sm:text-base text-ivory-muted leading-relaxed">Cette scène fait passer la compassion avant les querelles et montre l’entraide entre voisines.</p></div>
      <div className="rounded-2xl border border-warm/15 bg-warm/[0.04] px-5 py-4 mb-5"><p className="text-sm sm:text-base text-ink-muted dark:text-ivory-muted leading-relaxed"><strong className="text-ink dark:text-ivory">Note de lecture :</strong> {chapter.note}</p></div>
      <div className="mt-6 flex items-center gap-4 border-l-2 border-warm/50 pl-5 py-2"><MapPin size={19} className="text-warm-dark dark:text-gold-light shrink-0"/><p className="text-base sm:text-lg text-ink-muted dark:text-ivory-muted leading-relaxed"><strong className="text-ink dark:text-ivory">L’idée de Rayan :</strong> Dar Chouafa fonctionne comme une petite communauté; la proximité des familles rend possibles les disputes, les nouvelles et l’entraide.</p></div>
    </div>
  </section>;
}

function WiderCircleChapter({ chapter }: { chapter: Chapter }) {
  const storyPeople = chapter.people.slice(2, 4);
  const distinctionPeople = chapter.people.slice(4);
  return <section id={chapter.id} className="section-pad relative pt-8 scroll-mt-20">
    <div className="max-w-6xl mx-auto px-4 sm:px-6">
      <div className="grid md:grid-cols-[auto_1fr] gap-5 items-end mb-8"><div className="font-serif text-7xl sm:text-8xl text-warm/35 dark:text-gold/35 leading-none">04</div><div><div className="eyebrow mb-4"><span className="w-1 h-1 rounded-full bg-warm"/>Lgharib · dernier chapitre</div><h2 className="font-serif text-4xl sm:text-5xl md:text-6xl text-ink dark:text-ivory leading-[1.04]">Les liens, les récits, <span className="italic text-ink-light dark:text-ivory-muted">les échos</span></h2><p className="mt-3 text-xs sm:text-sm uppercase tracking-[0.17em] text-warm-dark dark:text-gold-light">{chapter.subtitle}</p></div></div>
      <p className="max-w-4xl text-base sm:text-lg text-ink-muted dark:text-ivory-muted leading-relaxed mb-7">{chapter.intro}</p>
      <div className="grid lg:grid-cols-[0.9fr_1.1fr] gap-5 mb-7">
        <div className="rounded-[1.6rem] bg-ink dark:bg-obsidian-light text-cream dark:text-ivory p-7 sm:p-9 shadow-ambient relative overflow-hidden"><div className="absolute -right-5 -top-10 font-serif text-[12rem] leading-none text-white/[0.035]">“</div><div className="relative z-10"><div className="flex items-center gap-3 mb-5"><Mic2 size={18} className="text-gold-light"/><span className="text-[9px] uppercase tracking-[0.2em] text-gold-light">Prise de parole · Lgharib</span></div><p className="text-lg sm:text-xl leading-[1.8] text-ivory">{chapter.talk}</p></div></div>
        <div className="bezel-outer shadow-ambient-sm"><div className="bezel-inner p-6 sm:p-8 h-full"><div className="flex items-center gap-3 mb-6"><Network size={19} className="text-warm-dark dark:text-gold-light"/><h3 className="font-serif text-2xl text-ink dark:text-ivory">Réseau des histoires</h3></div>
          <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="rounded-2xl border border-warm/20 bg-warm/[0.045] p-4 text-center"><p className="font-serif text-lg sm:text-xl text-ink dark:text-ivory">Lalla Zoubida</p><p className="text-xs text-ink-muted dark:text-ivory-muted">famille du narrateur</p></div><ArrowRight size={17} className="text-warm-dark dark:text-gold-light"/><div className="rounded-2xl border border-warm/20 bg-warm/[0.045] p-4 text-center"><p className="font-serif text-lg sm:text-xl text-ink dark:text-ivory">Lalla Aïcha</p><p className="text-xs text-ink-muted dark:text-ivory-muted">amie et confidente</p></div></div>
          <div className="flex justify-center py-3"><ArrowDown size={17} className="text-warm-dark dark:text-gold-light"/></div>
          <div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-ink/8 dark:border-white/10 p-4 text-center"><p className="font-serif text-lg text-ink dark:text-ivory">Moulay Larbi</p><p className="text-xs text-ink-muted dark:text-ivory-muted">son histoire de ménage et de travail</p></div><div className="rounded-2xl border border-ink/8 dark:border-white/10 p-4 text-center"><p className="font-serif text-lg text-ink dark:text-ivory">Salama</p><p className="text-xs text-ink-muted dark:text-ivory-muted">marieuse liée à l’épisode</p></div></div>
          <p className="mt-4 text-xs text-ink-faint dark:text-ivory-faint text-center">Les nouvelles circulent par les visites et les conversations.</p>
        </div></div>
      </div>
      <div className="grid md:grid-cols-2 gap-5 mb-6">
        <div className="bezel-outer"><div className="bezel-inner p-6 sm:p-7 h-full"><div className="flex items-center gap-3 mb-5"><BookOpen size={18} className="text-warm-dark dark:text-gold-light"/><div><p className="text-[9px] uppercase tracking-[0.17em] text-warm-dark dark:text-gold-light">La parole qui ouvre des mondes</p><h3 className="font-serif text-xl sm:text-2xl text-ink dark:text-ivory">Récits transmis</h3></div></div>{storyPeople.map((person) => <div key={person.name} className="py-3 border-t border-ink/5 dark:border-white/8 first:border-0"><h4 className="font-serif text-lg text-ink dark:text-ivory">{person.name}</h4><p className="text-[9px] uppercase tracking-[0.13em] text-warm-dark dark:text-gold-light my-1">{person.role}</p><p className="text-sm sm:text-base text-ink-muted dark:text-ivory-muted leading-relaxed">{person.detail}</p></div>)}<div className="mt-4 rounded-xl bg-warm/[0.05] p-4"><p className="text-sm text-ink-muted dark:text-ivory-muted"><strong className="text-ink dark:text-ivory">Histoire enchâssée :</strong> Rahma raconte un épisode mettant en scène Sidi Othmane et Lalla Khadija.</p></div></div></div>
        <div className="bezel-outer"><div className="bezel-inner p-6 sm:p-7 h-full"><div className="flex items-center gap-3 mb-5"><Sparkles size={18} className="text-warm-dark dark:text-gold-light"/><div><p className="text-[9px] uppercase tracking-[0.17em] text-warm-dark dark:text-gold-light">Repères pour ne pas confondre</p><h3 className="font-serif text-xl sm:text-2xl text-ink dark:text-ivory">Deux figures, deux fonctions</h3></div></div>{distinctionPeople.map((person, index) => <div key={person.name} className={`flex gap-4 py-4 ${index ? 'border-t border-ink/5 dark:border-white/8' : ''}`}><span className="font-serif text-2xl text-warm-dark dark:text-gold-light">0{index + 1}</span><div><h4 className="font-serif text-lg text-ink dark:text-ivory">{person.name}</h4><p className="text-[9px] uppercase tracking-[0.13em] text-warm-dark dark:text-gold-light my-1">{person.role}</p><p className="text-sm sm:text-base text-ink-muted dark:text-ivory-muted leading-relaxed">{person.detail}</p></div></div>)}<div className="mt-3 rounded-xl border border-ink/7 dark:border-white/8 p-4"><p className="text-xs sm:text-sm text-ink-muted dark:text-ivory-muted leading-relaxed">{chapter.note}</p></div></div></div>
      </div>
      {chapter.extras && <div className="flex gap-4 items-start px-1 py-3 mb-5"><Eye size={18} className="mt-1 text-warm-dark dark:text-gold-light shrink-0"/><p className="text-sm sm:text-base text-ink-muted dark:text-ivory-muted leading-relaxed"><strong className="text-ink dark:text-ivory">Personnages plus ponctuels :</strong> {chapter.extras}</p></div>}
      <div className="mt-7 overflow-hidden rounded-[1.5rem] border border-warm/15"><div className="bg-warm/[0.07] px-5 py-4 flex items-center gap-3"><Network size={17} className="text-warm-dark dark:text-gold-light"/><h3 className="font-serif text-xl text-ink dark:text-ivory">Le fil des personnages à retenir</h3></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 divide-y sm:divide-y-0 sm:divide-x divide-ink/6 dark:divide-white/8 bg-white/30 dark:bg-white/[0.02]">{chapter.board.map((line, i) => <div key={line} className="p-5"><span className="font-serif text-3xl text-warm-dark/45 dark:text-gold-light/50">0{i + 1}</span><p className="mt-2 text-sm sm:text-base text-ink-muted dark:text-ivory-muted leading-relaxed">{line}</p></div>)}</div></div>
    </div>
  </section>;
}

export default function ProjectChapters() {
  const family = chapters[0];
  const neighbours = chapters[1];
  const widerCircle = chapters[2];
  return <div className="relative">
    <section className="section-pad relative pb-8"><SectionNumber number="02—04"/><div className="max-w-6xl mx-auto px-4 sm:px-6 text-center"><div className="eyebrow mb-6"><span className="w-1 h-1 rounded-full bg-warm"/>La galerie des personnages</div><h2 className="font-serif text-4xl sm:text-5xl md:text-6xl text-ink dark:text-ivory leading-[1.05]">Trois façons de lire <span className="italic text-ink-light dark:text-ivory-muted">un même monde</span></h2><p className="mt-5 max-w-3xl mx-auto text-base sm:text-lg text-ink-muted dark:text-ivory-muted leading-relaxed">La famille révèle le regard du narrateur; la maison organise le voisinage; les récits des adultes ouvrent la porte à toute la médina.</p></div></section>
    <FamilyChapter chapter={family}/>
    <NeighbourChapter chapter={neighbours}/>
    <WiderCircleChapter chapter={widerCircle}/>
    <section className="section-pad pt-10"><div className="max-w-5xl mx-auto px-4 sm:px-6"><motion.div initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.65 }} className="bezel-outer shadow-ambient"><div className="bezel-inner p-7 sm:p-10 md:p-12"><div className="eyebrow mb-6"><span className="w-1 h-1 rounded-full bg-warm"/>Conclusion · à dire en dernier</div><h2 className="font-serif text-3xl sm:text-4xl text-ink dark:text-ivory mb-5">Que nous apprend cette galerie ?</h2><p className="text-lg sm:text-xl text-ink-muted dark:text-ivory-muted leading-[1.8]">Les personnages ne sont pas une simple liste : ils construisent le monde dont Sidi Mohammed se souvient. Sa famille porte l’intrigue principale; les voisins font apparaître la solidarité et les tensions de la vie collective; les histoires rapportées donnent une place importante à la mémoire et à la parole. Grâce au regard de l’enfant, Fès devient à la fois un lieu réel et un univers transformé par le souvenir et l’imagination.</p><div className="grid md:grid-cols-3 gap-4 mt-8"><div className="rounded-2xl border border-ink/6 dark:border-white/8 p-5"><BookOpen size={19} className="text-warm-dark dark:text-gold-light mb-3"/><h3 className="font-serif text-xl text-ink dark:text-ivory mb-2">Le point de vue</h3><p className="text-base text-ink-muted dark:text-ivory-muted leading-relaxed">Une enfance racontée à la première personne, avec une mémoire adulte en arrière-plan.</p></div><div className="rounded-2xl border border-ink/6 dark:border-white/8 p-5"><Heart size={19} className="text-warm-dark dark:text-gold-light mb-3"/><h3 className="font-serif text-xl text-ink dark:text-ivory mb-2">Les relations</h3><p className="text-base text-ink-muted dark:text-ivory-muted leading-relaxed">Famille, amitié, voisinage, entraide et conflits ordinaires.</p></div><div className="rounded-2xl border border-ink/6 dark:border-white/8 p-5"><MessageCircle size={19} className="text-warm-dark dark:text-gold-light mb-3"/><h3 className="font-serif text-xl text-ink dark:text-ivory mb-2">La parole</h3><p className="text-base text-ink-muted dark:text-ivory-muted leading-relaxed">Les confidences, contes et souvenirs ouvrent le roman sur plusieurs voix.</p></div></div></div></motion.div></div></section>
  </div>;
}
